"""generate changes

Revision ID: a9f3e92d440c
Revises: ad4d38f7f49e
Create Date: 2022-03-21 17:20:23.416501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9f3e92d440c'
down_revision = 'ad4d38f7f49e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Links_owner_id_fkey', 'Links', type_='foreignkey')
    op.create_foreign_key(None, 'Links', 'Users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Links', type_='foreignkey')
    op.create_foreign_key('Links_owner_id_fkey', 'Links', 'Users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
