"""generate changes

Revision ID: ad4d38f7f49e
Revises: 35b5514a3a87
Create Date: 2022-03-20 16:41:25.053311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad4d38f7f49e'
down_revision = '35b5514a3a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
